### ISSUE TITLE
Upgrade boost version from 1.58 to 1.63

### ISSUE THREAD

**Issue by bitbytedog** [Cogosense/iOSBoostFramework#1]
There are increasing number of boost related crashes on HockeyApp. Upgrade to latest version of boost to see if this improves the situation.

**Comment by bitbytedog** [comment]
Added boost library version to the diagnostics status screen. Use this to confirm correct version of boost is used.

**Comment by CogoAlpha1** [comment]
Confirmed on iOS client build 4.0.4.606
