### ISSUE TITLE
Build a universal static library

### ISSUE THREAD

**Issue by donaldking** [Cogosense/iOSBoostFramework#6]
Hi, can you please point me to the steps to follow to build this as a static library?

**Comment by bitbytedog** [comment]
Currently only a static framework is supported. There are three ways to build it - command line, Xcode workspace, and Carthage. Carthage is the way we use it.

## Carthage

Create a Cartfile in your project top level directory with the following in it:

    github "Cogosense/iOSBoostFramework" >= 1.68.0

run the command

    carthage bootstrap --platform iOS --cache-builds

To build it (I add this as a Build Phase in Xcode)

![Screen Shot 2019-03-22 at 10 42 27 PM](https://user-images.githubusercontent.com/2413852/54862167-dcff6600-4cf3-11e9-9332-830042627212.png)

Finally under "Link binary with libraries" add the "boost.framework", it will be found under the directory **Carthage/Build/iOS**.

![Screen Shot 2019-03-22 at 10 43 42 PM](https://user-images.githubusercontent.com/2413852/54862232-de7d5e00-4cf4-11e9-9130-d9fb64955663.png)

## Xcode Workspace

From finder, drag **iOSBoostFramework.xcodeproj** into the workspace pane on the left.

## Command line
Make sure you have the Xcode commandline tools installed

    make

By default it contains the arm64 and arm7 architectures and bitcode is off. The framework is archived into a tarball **boost.framework.tar.bz2**. Extract it anywhere you want and add it in the Xcode project under "Link binary with libraries".

If you want more architectures:

    make ARCHS="x86_64 i386 arm64 armv7 armv7s"

If you want bitcode

    make ENABLE_BITCODE=YES BITCODE_GENERATION_MODE=bitcode
