### ISSUE TITLE
Supporting latest boost library (e.g. 1.71+)

### ISSUE THREAD

**Issue by mrayy** [Cogosense/iOSBoostFramework#7]
In order to build this framework to support the newer versions of boost, 
what are the steps or things should be modified to do?

**Comment by bitbytedog** [comment]
I was working on 1_73_0 but got distracted. I should be able to get back to it soon.

**Comment by bitbytedog** [comment]
I have created a branch with my current work on 1.73.0 (**1_73_0_dev**).

Check it out and just issue the command `make` in the top level directory, it will build you a tarball containing a boost framework. The following libraries are enabled:

~~~~
    - atomic                   : building
    - chrono                   : building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : building
    - exception                : building
    - fiber                    : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - locale                   : building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - nowide                   : not building
    - program_options          : building
    - python                   : not building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - stacktrace               : not building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building
~~~~

All arm and simulator variants are built, so it takes a bit longer than embedding it as a project in a workspace. The minimum iOS version has been bumped from 8.0 to 10.0 to solve a problem with `std:: uncaught_exceptions()` which was missing from libc++ on iOS 8.0 and maybe 9.0.

I will be testing the new version on our app over the next few weeks and creating any patches for warnings found. When it is ready I will create a release and a binary package for carthage.

**Comment by mrayy** [comment]
Thank you @bitbytedog for the update!

I was able to successfully build and test the 1.73.0 version.
