### ISSUE TITLE
Application crash when use the boost.framework

### ISSUE THREAD

**Issue by mamunabcoder** [Cogosense/iOSBoostFramework#9]
I have used Xcode 13.0 or later.
 
 Below error found when used boost.framework
 
 **libc++abi.dylib: terminating with uncaught exception of type boost::archive::archive_exception: output stream error
terminating with uncaught exception of type boost::archive::archive_exception: output stream error**

Please help me to solve this issues

**Comment by bitbytedog** [comment]
updated to v1.73.0 - let me know if it fixes the issue.
